version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

python:
  version: "3.7"
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
    - method: setuptools
      path: TenBagger
