portfolio:
  stocks: {
             "ABBV": 17,
             "SONO": 50,
             "T": 132,
             "IBM": 56,
             "BLOK": 5.31,
             "HITIF": 1160, 
             "U": 16,
             "MRK": 3
              }

  crypto: {"ETH": 2.26}
