portfolio:
  stocks: {
            "HITIF": 4310,
            "SONO": 100,
             "T": 132,
             "GILT": 50,
             "IBM": 56,
             "NVDA": 8,
             "BLOK": 5.31
              }
  crypto: {"ETH-USD": 0.16}
