portfolio:
  stocks: {
             "ABBV": 17,
             "SONO": 100,
             "T": 132,
             "GILT": 50,
             "IBM": 56,
             "BLOK": 5.31,
             "HITIF": 7810
              }

  crypto: {"ETH": 2.16}
