aram: 
  "ABBV": 17
  "IBM": 56
  'TSM': 10
  "ETH-USD": 2.26
  "MRK": 33 
  "KMI": 80
  "DOT1-USD": 40
  "WPC": 30
  "AHH": 20
  "GNL": 15
  "VZ": 30
  "PFE": 40 
  "MO": 11
  "ALGO-EUR": 8184
               

testing:
  "ETH-USD": 2.26
  "ALGO-EUR": 280
  "IBM": 56

test_calculator:
  aapl: 50
  eth-usd: 10  

test_calculator2:
  aapl: 1
  ibm: 1
  eth-usd: 1
  algo-eur: 1
