commodities: {"Gold": "GC=F",
              "Silver": "SI=F",
              "Natual Gas": "NG=F",
              "Crude Oil": "CL=F",
              "Copper": "HG=F",
              "Platinum": "PL=F",
              "Aluminium": "ALI=F",
              "Wheat": "ZW=F",
              "Corn": "ZC=F",
              "Coffee": "KC=F",
              "Sugar": "SF=F"
}

indices: {"Netherlands AEX": "^AEX",
          "S&P 500": "^GSPC",
          "Dow Jones": "^DJI",
          "NASDAQ": "^IXIC",
          "EURONEXT 100": "^N100",
          "German DAX": "^GDAXI",
          "London 100": "^FTSE",
          "France CAC": "^FCHI",
          "Japan Nikkei 225": "^N225",
          "Hong Kong Hang Seng": "^HSI"}

              
Region: {"Europe": "VGK",
          "China": "CHIX"}

Industries: {"Online retail": "ONLN",
              "Blockchain": "BLOK", 
              "Global X Internet of Things": "SNSR"}
