commodities: {"Gold": "GC=F",
              "Silver": "SI=F",
              "Natual Gas": "NG=F",
              "Crude Oil": "CL=F",
              "Copper": "HG=F",
              "Platinum": "PL=F",
              "Palladium": "PA=F",
              "Aluminium": "ALI=F",
              "Wheat": "ZW=F",
              "Corn": "ZC=F",
              "Coffee": "KC=F",
              "Sugar": "SF=F"
}

HedgeFunds: {
  "Berkshire Hathaway": "BRK-B",
  "Blackrock Inc": "BLK",
  "Morgan Stanley": "MS"

}

indices: {"Netherlands  AEX": "^AEX",
          "S&P 500": "^GSPC",
          "Dow Jones": "^DJI",
          "NASDAQ": "^IXIC",
          "EURONEXT 100": "^N100",
          "German DAX": "^GDAXI",
          "London 100": "^FTSE",
          "France CAC": "^FCHI",
          "Japan Nikkei 225": "^N225",
          "Hong Kong Hang Seng": "^HSI"}

              
Region: {"Europe": "VGK",
          "China": "CHIX"}

ETF: {"Ark Innovation": "ARKK",
"Ark Genomic": "ARKG",
"Ark Fintech": "ARKF",
"Ark Next internet": "ARKW",
"ARK AT & Robotics": "ARKQ",}
"Emerging Markets": "EEM"


Industries: {"Online retail": "ONLN",
              "Blockchain": "BLOK", 
              "Global X Internet of Things": "SNSR",
              "Weed MJ": "MJ",
              "Weed Canada": "HMMJ.TO",
}
