Tech: 
{
  "Unity": "U"
}

Space:
  {
    "Maxar": "MAXR",
    "Virgin Galactic": "SPCE"
  }

BioScience:
  {
    "Evofem": "EVFM"

  }

REIT: {
  "GEO": 1,
  "AHH": ,
  "STOR": ,
  "WPC" : 
  "GNL;"
